# Generated by Django 5.1.3 on 2024-11-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0003_product_explanation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="img",
            field=models.ImageField(
                blank=True, default="noImage.png", upload_to="images/"
            ),
        ),
    ]
