# Generated by Django 5.1.3 on 2024-11-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0005_alter_product_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="img",
            field=models.ImageField(blank=True, default="noImage.png", upload_to=""),
        ),
    ]
