# Generated by Django 5.1.3 on 2024-11-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0009_alter_product_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="img",
            field=models.ImageField(
                blank=True, default="images/noImage.png", upload_to="images"
            ),
        ),
    ]
